### PR TITLE
Vignette row names

### PR DESCRIPTION
**Pull request by wibeasley**
Thanks for creating this package, @jtilly.  I found the documentation very helpful too.  I'm just learning the concepts and terminology, so my feelings won't be hurt if you reject this PR.  

In the two-sided market section of the vignette, the row names for a *utility* matrix are `Woman 1` ...`Woman 3`.  But if I understand correctly, the rows of the *preference* matrix represent something different.  Are the terms `Preference 1`...`Preference 3` more representative?

The two modifications to the Rmd file are the only real changes I made.  The others appear to be the result of how Rcpp auto-generates some code differently.

### CODE REVIEW

**Comment by jtilly** [comment]
Thanks, Will. You're making a good point. We should come up with better
row/column names to make clear what's going on. I'm not sure if I like
Preference 1, 2, ...

We could probably just number the rows instead.

While we're at it, we should also change the row/column names of `uM` and
`uW` to make clear whose payoffs we're describing.

**Comment by wibeasley** [comment]
If there's something else you'd like it named, just tell me.  It's still set up on my computer.

**Comment by jtilly** [comment]
Thanks, I already managed to sneak a little change in before I merged.

I'm now going with
```
##         cols
## rows     Woman 1 Woman 2 Woman 3
##   Rank 1       3       1       3
##   Rank 2       2       3       2
##   Rank 3       1       2       1
```

**Comment by wibeasley** [comment]
oh good, I like the brevity of "Rank X" better too.

**Pull request merged**
